# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 101

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 102

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 103

[[main]]
  name = "Conferences"
  url = "#conferences"
  weight = 104
 
[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 105
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 106

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
